add github action workflow

diff --git a/.github/workflows/test_role.yml b/.github/workflows/test_role.yml
--- a/.github/workflows/test_role.yml
+++ b/.github/workflows/test_role.yml
@@ -257,20 +257,25 @@ jobs:
     steps:
     - name: Clone repository
       uses: actions/checkout@v2
-    
-    - name: Set up Ruby 2.6
-      uses: actions/setup-ruby@v1
-      with:
-        ruby-version: 2.6
 
     - name: Install Inspec
-      run: bundle install
+      run: gem install inspec-bin -v 4.16.0
 
-    - name: Test Ansible role Java
+    - name: Run container and mount Ansible role with it
       run: |
         container_id=$(mktemp)
         sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-role-java:ro diodonfrost/${{ matrix.config.distribution }}-ansible:latest > "${container_id}"
-        sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-java/tests/playbooks/${{ matrix.config.playbook }}.yml --syntax-check
-        sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-java/tests/playbooks/${{ matrix.config.playbook }}.yml
-        sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-java/tests/playbooks/${{ matrix.config.playbook }}.yml | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
-        inspec exec tests/inspec --chef-license accept-silent -t docker://$(cat ${container_id})
+
+    - name: Check syntax
+      run: sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-java/tests/playbooks/${{ matrix.config.playbook }}.yml --syntax-check
+
+    - name: Run Ansible playbook
+      run: sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-java/tests/playbooks/${{ matrix.config.playbook }}.yml
+
+    - name: Test indempotence
+      run: |
+        sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-java/tests/playbooks/${{ matrix.config.playbook }}.yml \
+        | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
+
+    - name: Test role
+      run: inspec exec tests/inspec --chef-license accept-silent -t docker://$(cat ${container_id})
